# TODO: If you are running into any issues during startup, uncomment
# the following line.
# debug: true
logging:
  pattern:
    console: "%d [%t] %-5p - %m%n"
spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true

management:
  endpoint:
    health:
        show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - env
          - metrics
---
spring:
  profiles: "local"
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password:
    driver-class-name: "org.h2.Driver"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
spring:
  profiles: "mysql"
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
            default_schema: "amielz"
